# coding: utf-8

"""
    Car Rental Api

    Rest api for car rental  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: mabtuhanilhan@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.api_error import ApiError  # noqa: E501
from swagger_client.rest import ApiException


class TestApiError(unittest.TestCase):
    """ApiError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiError(self):
        """Test ApiError"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.api_error.ApiError()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
