# coding: utf-8

"""
    Car Rental Api

    Rest api for car rental  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: mabtuhanilhan@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.reservation_api import ReservationApi  # noqa: E501
from swagger_client.rest import ApiException


class TestReservationApi(unittest.TestCase):
    """ReservationApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.reservation_api.ReservationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_reservation_post(self):
        """Test case for reservation_post

        Make reservation  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
