# coding: utf-8

"""
    Car Rental Api

    Rest api for car rental  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: mabtuhanilhan@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.make_reservation_request import MakeReservationRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestMakeReservationRequest(unittest.TestCase):
    """MakeReservationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMakeReservationRequest(self):
        """Test MakeReservationRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.make_reservation_request.MakeReservationRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
