# Generated by Django 3.2.9 on 2022-01-23 21:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unavailability',
            name='end_datetime',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unavailability',
            name='start_datetime',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
