# Generated by Django 3.2.9 on 2022-01-29 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0002_auto_20220124_0039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unavailability',
            old_name='car_id',
            new_name='car',
        ),
    ]
