# Generated by Django 3.2.9 on 2021-12-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_car_yıl'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='koltuk_sayisi',
            field=models.IntegerField(default=5, verbose_name=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='modell',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='vites_tipi',
            field=models.CharField(default='manuel', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='yakit_tipi',
            field=models.CharField(default='benzin', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='yil',
            field=models.IntegerField(default=2021, verbose_name=2021),
            preserve_default=False,
        ),
    ]
