# Generated by Django 3.2.9 on 2022-01-28 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20220128_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='yil',
            new_name='year',
        ),
    ]
