# Generated by Django 3.2.9 on 2021-12-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20211223_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='koltuk_sayisi',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='yil',
            field=models.IntegerField(),
        ),
    ]
