# Generated by Django 3.2.9 on 2021-12-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20211223_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='konfor',
            field=models.IntegerField(null=True),
        ),
    ]
