# Generated by Django 3.2.9 on 2022-02-27 21:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_carmodel_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='year',
            field=models.IntegerField(default=2021, validators=[django.core.validators.MaxValueValidator(limit_value=2022)]),
        ),
    ]
