# Generated by Django 3.2.9 on 2021-12-29 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_car_konfor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='konfor',
        ),
    ]
