# Generated by Django 3.2.9 on 2022-03-05 13:18

import cars.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_carmodel_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='year',
            field=models.IntegerField(default=2021, validators=[cars.models.max_year_validator]),
        ),
    ]
