# Generated by Django 3.2.9 on 2021-12-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_remove_car_konfor'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='sinif',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
    ]
