# Generated by Django 3.2.9 on 2021-12-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_car_sinif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='koltuk_sayisi',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='car',
            name='yil',
            field=models.IntegerField(default=2021),
        ),
    ]
