# Generated by Django 3.2.9 on 2021-12-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ulke', models.CharField(max_length=50)),
                ('sehir', models.CharField(max_length=50)),
                ('adres', models.CharField(max_length=400)),
            ],
        ),
    ]
