# Generated by Django 3.2.9 on 2022-04-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
