# Generated by Django 3.2.9 on 2022-04-15 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0002_office_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='phone_number',
        ),
    ]
