# Generated by Django 3.2.9 on 2022-03-06 13:27

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('identity_number', models.CharField(max_length=11, validators=[user.models.identity_number_length_validator])),
                ('phone_number', models.CharField(max_length=10, validators=[user.models.phone_number_length_validator])),
                ('date_of_birth', models.DateField(validators=[user.models.date_of_birth_validator])),
                ('email_address', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
