# Generated by Django 3.2.9 on 2022-03-08 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
    ]
