# Generated by Django 3.2.9 on 2022-03-18 12:23

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20220318_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[user.models.date_of_birth_validator]),
        ),
        migrations.AlterField(
            model_name='user',
            name='identity_number',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[user.models.identity_number_length_validator]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[user.models.phone_number_length_validator]),
        ),
    ]
