# Generated by Django 3.2.9 on 2022-04-15 14:41

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20220318_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(validators=[user.models.date_of_birth_validator]),
        ),
        migrations.AlterField(
            model_name='user',
            name='identity_number',
            field=models.CharField(max_length=11, validators=[user.models.identity_number_length_validator]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[user.models.phone_number_length_validator]),
        ),
    ]
