# Generated by Django 3.2.9 on 2022-03-06 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0007_alter_carmodel_year'),
        ('offices', '0001_initial'),
        ('availability', '0003_rename_car_id_unavailability_car'),
        ('user', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_up_date', models.DateField()),
                ('drop_off_date', models.DateField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offices.office')),
                ('unavailability', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='availability.unavailability')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
