# Generated by Django 3.2.9 on 2022-01-29 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0003_rename_car_id_unavailability_car'),
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='name_of_the_customer',
            field=models.CharField(default='Batuhan Ilhan', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='tel_number_of_the_customer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='unavailability',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='availability.unavailability'),
            preserve_default=False,
        ),
    ]
