# Generated by Django 3.2.9 on 2022-01-29 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20220129_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='name_of_the_customer',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='tel_number_of_the_customer',
        ),
    ]
