# Generated by Django 3.2.9 on 2022-01-29 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_auto_20220129_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='unavailability',
        ),
    ]
