# Generated by Django 3.2.9 on 2022-01-29 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0003_rename_car_id_unavailability_car'),
        ('reservation', '0004_remove_reservation_unavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='unavailability',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='availability.unavailability'),
            preserve_default=False,
        ),
    ]
