# coding: utf-8

"""
    Car Rental Api

    Rest api for car rental  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: mabtuhanilhan@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class CarModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'year': 'int',
        'seat_count': 'int',
        'car_class': 'str',
        'brand': 'CarBrand'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'year': 'year',
        'seat_count': 'seat_count',
        'car_class': 'car_class',
        'brand': 'brand'
    }

    def __init__(self, id=None, name=None, year=None, seat_count=None, car_class=None, brand=None, _configuration=None):  # noqa: E501
        """CarModel - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._id = None
        self._name = None
        self._year = None
        self._seat_count = None
        self._car_class = None
        self._brand = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if year is not None:
            self.year = year
        if seat_count is not None:
            self.seat_count = seat_count
        if car_class is not None:
            self.car_class = car_class
        if brand is not None:
            self.brand = brand

    @property
    def id(self):
        """Gets the id of this CarModel.  # noqa: E501

        uniq identifier  # noqa: E501

        :return: The id of this CarModel.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this CarModel.

        uniq identifier  # noqa: E501

        :param id: The id of this CarModel.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this CarModel.  # noqa: E501


        :return: The name of this CarModel.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CarModel.


        :param name: The name of this CarModel.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def year(self):
        """Gets the year of this CarModel.  # noqa: E501


        :return: The year of this CarModel.  # noqa: E501
        :rtype: int
        """
        return self._year

    @year.setter
    def year(self, year):
        """Sets the year of this CarModel.


        :param year: The year of this CarModel.  # noqa: E501
        :type: int
        """

        self._year = year

    @property
    def seat_count(self):
        """Gets the seat_count of this CarModel.  # noqa: E501


        :return: The seat_count of this CarModel.  # noqa: E501
        :rtype: int
        """
        return self._seat_count

    @seat_count.setter
    def seat_count(self, seat_count):
        """Sets the seat_count of this CarModel.


        :param seat_count: The seat_count of this CarModel.  # noqa: E501
        :type: int
        """

        self._seat_count = seat_count

    @property
    def car_class(self):
        """Gets the car_class of this CarModel.  # noqa: E501


        :return: The car_class of this CarModel.  # noqa: E501
        :rtype: str
        """
        return self._car_class

    @car_class.setter
    def car_class(self, car_class):
        """Sets the car_class of this CarModel.


        :param car_class: The car_class of this CarModel.  # noqa: E501
        :type: str
        """

        self._car_class = car_class

    @property
    def brand(self):
        """Gets the brand of this CarModel.  # noqa: E501


        :return: The brand of this CarModel.  # noqa: E501
        :rtype: CarBrand
        """
        return self._brand

    @brand.setter
    def brand(self, brand):
        """Sets the brand of this CarModel.


        :param brand: The brand of this CarModel.  # noqa: E501
        :type: CarBrand
        """

        self._brand = brand

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CarModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CarModel):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CarModel):
            return True

        return self.to_dict() != other.to_dict()
