# coding: utf-8

"""
    Car Rental Api

    Rest api for car rental  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: mabtuhanilhan@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class OfficeRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'country': 'str',
        'city': 'str',
        'address': 'str'
    }

    attribute_map = {
        'id': 'id',
        'country': 'country',
        'city': 'city',
        'address': 'address'
    }

    def __init__(self, id=None, country=None, city=None, address=None, _configuration=None):  # noqa: E501
        """OfficeRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._id = None
        self._country = None
        self._city = None
        self._address = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if country is not None:
            self.country = country
        if city is not None:
            self.city = city
        if address is not None:
            self.address = address

    @property
    def id(self):
        """Gets the id of this OfficeRequest.  # noqa: E501


        :return: The id of this OfficeRequest.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this OfficeRequest.


        :param id: The id of this OfficeRequest.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def country(self):
        """Gets the country of this OfficeRequest.  # noqa: E501


        :return: The country of this OfficeRequest.  # noqa: E501
        :rtype: str
        """
        return self._country

    @country.setter
    def country(self, country):
        """Sets the country of this OfficeRequest.


        :param country: The country of this OfficeRequest.  # noqa: E501
        :type: str
        """

        self._country = country

    @property
    def city(self):
        """Gets the city of this OfficeRequest.  # noqa: E501


        :return: The city of this OfficeRequest.  # noqa: E501
        :rtype: str
        """
        return self._city

    @city.setter
    def city(self, city):
        """Sets the city of this OfficeRequest.


        :param city: The city of this OfficeRequest.  # noqa: E501
        :type: str
        """

        self._city = city

    @property
    def address(self):
        """Gets the address of this OfficeRequest.  # noqa: E501


        :return: The address of this OfficeRequest.  # noqa: E501
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this OfficeRequest.


        :param address: The address of this OfficeRequest.  # noqa: E501
        :type: str
        """

        self._address = address

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OfficeRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OfficeRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, OfficeRequest):
            return True

        return self.to_dict() != other.to_dict()
